Fix ADC 16 bit range
adafruit/Adafruit_CircuitPython_MCP3xxx pull request #44
Opened 2023-07-02 08:29 UTC by BiffoBear

Closes #43 by changing the scaling to `x * (65535 / 1023)` from the faster but less accurate `x << 6`

There is no mention of this in the MCP3008 learning guide, so the guide shouldn't need updating.

2023-07-31 21:28 UTC, tannewt commented
Another way to fill in the bottom bits is to [repeat the top bits there:](https://github.com/adafruit/circuitpython/blob/272a2dcdb0230cd13a6c7cc974805a919ef13a8d/ports/atmel-samd/common-hal/analogio/AnalogIn.c#L127)

```c
// Stretch 12-bit ADC reading to 16-bit range
return (value << 4) | (value >> 8);
```

2023-09-21 19:10 UTC, dhalbert requested changes

2023-09-21 19:10 UTC, dhalbert commented on adafruit_mcp3xxx/analog_in.py
> +            * (65535 / 1023)
This incorporates @tannewt's suggestion to use a slightly different technique:
```suggestion
        # Initial result is only 10 bits.
        result = int(self._mcp.read(self._pin_setting, is_differential=self.is_differential))
        # Stretch to 16 bits and cover full range.
        return (result << 6) | (result >> 4)
```

2023-09-21 19:43 UTC, dhalbert approved these changes
Thanks for the initial fix!

2023-09-21 19:43 UTC, merged